//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "attribute")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub kind: String,
    pub label: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attribute_option::Entity")]
    AttributeOption,
    #[sea_orm(has_many = "super::product_attribute::Entity")]
    ProductAttribute,
}

impl Related<super::attribute_option::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttributeOption.def()
    }
}

impl Related<super::product_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductAttribute.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
